# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0082752e631ab68aa64374a850c0aca960fdf8352e61d45ce22ff50036e3b4a1e027d2cfedc17b6ca2e3d9806f5f7ef56b14467540e250711418f407a160bd5a

test:
  secret_key_base: ad0f4961a5dedb0b78ff271ed26baa87c5eae927eee85cea7c47d1fc8b745726a7f8a7c3bb7ecff839210c39e3b0e19eacf275d847f4ae3974ef4eed3ad81dce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
